 version: '3.7'
 services:
  
   dashboard:
     build: 
       context: ./
     container_name: ${COMPOSE_PROJECT_NAME}_Esp_app_dashboard
     restart: always
     ports:
       - 5000:80
     networks:
       - network 
    
 networks:
   network:
     driver: bridge